language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 5.6
        - php: 7.0
    fast_finish: true

before_script:
    - composer self-update
    - composer update

script:
    - ./bin/phpcs --standard=vendor/leaphub/phpcs-symfony2-standard/leaphub/phpcs/Symfony2/ --extensions=php src/
    - ./bin/phpunit